[package]
name = "qrstore"
version = "0.1.0"
authors = ["Arvid Böttiger <arvid@exensor.com>"]
edition = "2018"
autobins = false

#[lib]
#name = "qrstore"
#crate-type = ["rlib", "dylib"] # could be `staticlib` as well
#build = "build.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "rest"
path = "src/bin/rest.rs"

# AWS Lambda
[[bin]]
name = "bootstrap"
path = "src/bin/lambda.rs"

# AWS Lambda - Serverless
#[[bin]]
#name = "serverless"
#path = "src/bin/serverless.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
dotenv = "0.15"
rand  = "0.7"
chrono = "0.4"
clap = "2.33"
config = "0.10.1"

qrcode = "0.12"
image = "0.23.9"
#bardecoder = "0.2"
fxhash = "0.2.1"
printpdf = "0.3.2"

actix-web = "2.0"
actix-rt = "1.0.0"
env_logger = "0.7.1"

simple-error = "0.2.2"

rusoto_dynamodb = "0.44"
rusoto_core = "0.44"
rusoto_s3 = "0.44.0"
rusoto_credential = "0.44"

dynomite = "0.9.0"
dynomite-derive = "0.9.0"
futures = "0.3.5"
tokio = "0.2.22"
log = "0.4"
uuid = { version = "0.8", features = ["serde", "v5"] }

#rust-s3 = "0.22.12"

base64 = "0.12"
harsh = "0.1.6"

sha3 = "0.8.2"
bytes = "0.4.12"

# lambda
lambda_runtime = "0.2.1"
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"} #lambda_http = "0.1.1" #{ git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}

serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.115"
simple_logger = "1.7.0"