apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrst
  template:
    metadata:
      labels:
        app: qrst
    spec:
      containers:
      - name: qrst
        image: qrst:latest
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: qrst
spec:
  selector:
    app: qrst
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: NodePort
