FROM ekidd/rust-musl-builder as builder

# Add ARM target
RUN rustup target add aarch64-unknown-linux-musl

WORKDIR /home/rust/src
COPY --chown=rust ./Cargo* ./
COPY --chown=rust ./src ./src/

# Build for ARM
RUN cargo build --bin rest --release --target=aarch64-unknown-linux-musl

FROM alpine:latest AS app
# Copy in statically linked ARM binary
COPY --from=builder /home/rust/src/target/aarch64-unknown-linux-musl/release/rest /
EXPOSE 8088
ENTRYPOINT ["/rest"]
