CREATE TABLE qrcodes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  qr BIGINT NOT NULL,
  title VARCHAR,
  body TEXT,
  images TEXT,
  created_at DATETIME NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT 0
)
