name: Main

on: push

jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Source Code

      - name: Building and packaging AWS Lambda functions
        uses: miere/action-rust-aws-lambda@1.52.0
        id: rust-aws-lambda
        # Only required if your source is not in the root folder
        # By default, source-dir points to '.'
        #with:
        #  source-dir: "source"

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: arn:aws:lambda:eu-north-1:782562066078:function:qrwiki 
          zip_file: target/lambda/bootstrap2.zip
          runtime: provided.al2
          memory_size: 64
          dry_run: true
          #source: "target/lambda/bootstrap.zip"
          #qrwiki


      # Do something with the generated zip files
      # They will be generated at the target folder of your project.
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "{{process.env.GITHUB_RUN_ID}}"
          path: "target/lambda/*.zip"
          #path: "/github/workspace/target/lambda/*.zip"
          #path: "source/target/lambda/*.zip"